<div class="card">
    <div class="table-head">A/C, Component Surveillance</div>
    <div class="nano">
        <div class="nano-content">
            <button type="button" class="scalable add" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_surveillance/new')?>')" style=""><span><span><span>New Surveillance</span></span></span></button>
            <button type="button" class="scalable all" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_surveillance')?>')" style=""><span><span><span>All Surveillances</span></span></span></button>
        </div>
        <div class="nano-bottom">
            <h3>Latest Surveillances</h3>
            <div class="nano-content">
                We can show some latest surveillances here
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="table-head">RII Task/job sign-off</div>
    <div class="nano">
        <div class="nano-content">
            <button type="button" class="scalable add" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_rii/new')?>')" style=""><span><span><span>New RII Sign-off</span></span></span></button>
            <button type="button" class="scalable all" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_rii')?>')" style=""><span><span><span>All RII Sign-off</span></span></span></button>
        </div>
        <div class="nano-bottom">
            <h3>Latest RII Task/job sign-off</h3>
            <div class="nano-content">
                We can show some latest RII Task/job sign-off here
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="table-head">Sign-off Check</div>
    <div class="nano">
        <div class="nano-content">
            <button type="button" class="scalable add" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_signoff/new')?>')" style=""><span><span><span>New Sign-off Check</span></span></span></button>
            <button type="button" class="scalable all" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_signoff')?>')" style=""><span><span><span>All Sign-off Check</span></span></span></button>
        </div>
        <div class="nano-bottom">
            <h3>Latest Sign-off Check</h3>
            <div class="nano-content">
                We can show some latest Sign-off Check here
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="table-head">Investigation</div>
    <div class="nano">
        <div class="nano-content">
            <button type="button" class="scalable add" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_investigation/new')?>')" style=""><span><span><span>New Investigation</span></span></span></button>
            <button type="button" class="scalable all" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_investigation')?>')" style=""><span><span><span>All Investigation</span></span></span></button>
        </div>
        <div class="nano-bottom">
            <h3>Latest Investigation</h3>
            <div class="nano-content">
                We can show some latest Investigations here
            </div>
        </div>
    </div>
</div>

<hr>

<div class="card">
    <div class="table-head">Non-Conformity Report (NCR)</div>
    <div class="nano">
        <div class="nano-content">
            <button type="button" class="scalable add" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_ncr/new')?>')" style=""><span><span><span>New NCR</span></span></span></button>
            <button type="button" class="scalable all" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_ncr')?>')" style=""><span><span><span>All NCRs</span></span></span></button>
        </div>
        <div class="nano-bottom">
            <h3>Latest NCR</h3>
            <div class="nano-content">
                We can show some latest NCRs here
            </div>
        </div>
    </div>
</div>


<div class="card">
    <div class="table-head">Quality Request (QR/QN)</div>
    <div class="nano">
        <div class="nano-content">
            <button type="button" class="scalable add" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_qrqn/new')?>')" style=""><span><span><span>New QR/QN</span></span></span></button>
            <button type="button" class="scalable all" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_qrqn')?>')" style=""><span><span><span>All QR/QN</span></span></span></button>
        </div>
        <div class="nano-bottom">
            <h3>Latest QR/QN</h3>
            <div class="nano-content">
                We can show some latest QR/QNs here
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="table-head">Corrective Action Request (DRR)</div>
    <div class="nano">
        <div class="nano-content">
            <button type="button" class="scalable add" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_car/new')?>')" style=""><span><span><span>New DRR</span></span></span></button>
            <button type="button" class="scalable all" onclick="setLocation('<?php echo $this->getUrl('*/qualitycontrol_car')?>')" style=""><span><span><span>All DRR</span></span></span></button>
        </div>
        <div class="nano-bottom">
            <h3>Latest DRRs</h3>
            <div class="nano-content">
                We can show some latest DRRs here
            </div>
        </div>
    </div>
</div>

