<?php
$formKey = Mage::getSingleton('core/session')->getFormKey();
$url =  Mage::getUrl('*/wysiwyg/load', ['form_key' => $formKey]);
?>
<script>
if (typeof jQuery != 'undefined') {
    jQuery(document).ready(function(){
        jQuery('.textarea').redactor({
            imageUpload: '<?php echo $url; ?>',
            plugins: ['table','source','inlinestyle','alignment','fontsize','fontcolor','fullscreen'],
            imagePosition: true,
            imageResizable: true,
            buttonsHide: ['link']
        });
  });
}
</script>