<?php
define('SG_BACKUP_GUARD_VERSION', '1.0.1');

define('SG_FEATURE_DOWNLOAD_FROM_CLOUD', 1);
define('SG_FEATURE_STORAGE', 1);
define('SG_FEATURE_FTP', 1);
define('SG_FEATURE_AMAZON', 1);
define('SG_FEATURE_DROPBOX', 0);
define('SG_FEATURE_GOOGLE_DRIVE', 1);
define('SG_FEATURE_SCHEDULE', 1);
define('SG_FEATURE_DELETE_LOCAL_BACKUP_AFTER_UPLOAD', 1);
define('SG_FEATURE_NUMBER_OF_BACKUPS_TO_KEEP', 1);
define('SG_FEATURE_CUSTOM_BACKUP_NAME', 1);
define('SG_FEATURE_SUBDIRECTORIES', 1);
define('SG_FEATURE_BACKGROUND_MODE', 1);
define('SG_FEATURE_NOTIFICATIONS', 1);
define('SG_FEATURE_MULTI_SCHEDULE', 1);

define('SG_FEATURE_SHOW_UPGRADE_PAGE', 0);

